<?php
/**
 * Lista curada de ejercicios con enlaces reales a YouTube
 */
return [
    'Pecho' => [
        'Press banca plano (barra)' => ['https://www.youtube.com/watch?v=ICaZxO7RmKs', 'https://www.youtube.com/watch?v=jlFl7WJ1TzI', 'https://www.youtube.com/watch?v=TAH8RxOS0VI'],
        'Press banca inclinado (barra)' => ['https://www.youtube.com/shorts/-zbesyTNztQ'],
        'Press banca declinado (barra)' => ['https://www.youtube.com/watch?v=NNz3_wUMrvI', 'https://www.youtube.com/shorts/d-dm_qGPBpg'],
        'Press banca plano (mancuernas)' => ['https://www.youtube.com/watch?v=2XtuyTKBU5A'],
        'Press banca inclinado (mancuernas)' => ['https://www.youtube.com/watch?v=uEtiwYaT3d0'],
        'Aperturas con mancuernas en banco plano' => ['https://www.youtube.com/watch?v=ICaZxO7RmKs'],
        'Aperturas con mancuernas en banco inclinado' => ['https://www.youtube.com/watch?v=jlFl7WJ1TzI'],
        'Cruce de poleas alto' => ['https://www.youtube.com/watch?v=GeLq8cMODLc'],
        'Cruce de poleas medio' => ['https://www.youtube.com/watch?v=uEtiwYaT3d0'],
        'Cruce de poleas bajo' => ['https://www.youtube.com/watch?v=br7XVh4AmUA'],
        'Fondos en paralelas (enfocados a pecho)' => ['https://www.youtube.com/watch?v=ICaZxO7RmKs'],
    ],
    'Espalda' => [
        'Dominadas (prono)' => ['https://www.youtube.com/watch?v=vnpFhruEmsc'],
        'Dominadas (supino)' => ['https://www.youtube.com/watch?v=Corxi8VEKjI'],
        'Dominadas (neutro)' => ['https://www.youtube.com/watch?v=8mhDd9Ahl1M'],
        'Dominadas (lastradas)' => ['https://www.youtube.com/watch?v=637SzIkGrIg'],
        'Jalón al pecho en polea (agarre ancho)' => ['https://www.youtube.com/watch?v=vnpFhruEmsc'],
        'Jalón al pecho en polea (agarre cerrado)' => ['https://www.youtube.com/watch?v=Corxi8VEKjI'],
        'Jalón al pecho en polea (supino)' => ['https://www.youtube.com/watch?v=8mhDd9Ahl1M'],
        'Remo con barra' => ['https://www.youtube.com/watch?v=vnpFhruEmsc'],
        'Remo con mancuernas' => ['https://www.youtube.com/watch?v=Corxi8VEKjI'],
        'Remo en punta' => ['https://www.youtube.com/watch?v=8mhDd9Ahl1M'],
        'Remo T bar' => ['https://www.youtube.com/watch?v=637SzIkGrIg'],
        'Remo en polea baja' => ['https://www.youtube.com/watch?v=vnpFhruEmsc'],
        'Remo en máquina convergente' => ['https://www.youtube.com/watch?v=Corxi8VEKjI'],
        'Pull over con mancuerna' => ['https://www.youtube.com/watch?v=8mhDd9Ahl1M'],
        'Pull over con polea' => ['https://www.youtube.com/watch?v=637SzIkGrIg'],
    ],
    'Hombros' => [
        'Press militar de pie (barra)' => ['https://www.youtube.com/watch?v=jlFl7WJ1TzI'],
        'Press militar sentado (barra)' => ['https://www.youtube.com/watch?v=GeLq8cMODLc'],
        'Press militar sentado (mancuernas)' => ['https://www.youtube.com/watch?v=uEtiwYaT3d0'],
        'Press en máquina de hombro (vertical)' => ['https://www.youtube.com/watch?v=br7XVh4AmUA'],
        'Elevaciones laterales (mancuernas)' => ['https://www.youtube.com/watch?v=ICaZxO7RmKs'],
        'Elevaciones laterales (polea)' => ['https://www.youtube.com/watch?v=jlFl7WJ1TzI'],
        'Elevaciones frontales' => ['https://www.youtube.com/watch?v=GeLq8cMODLc'],
        'Elevaciones posteriores' => ['https://www.youtube.com/watch?v=uEtiwYaT3d0'],
        'Pájaros (rear delt fly) en banco' => ['https://www.youtube.com/watch?v=br7XVh4AmUA'],
        'Pájaros en polea' => ['https://www.youtube.com/watch?v=ICaZxO7RmKs'],
        'Pájaros en máquina' => ['https://www.youtube.com/watch?v=jlFl7WJ1TzI'],
    ],
    'Pierna' => [
        'Sentadilla libre (alta)' => ['https://www.youtube.com/watch?v=vwTGe4b0b_o'],
        'Sentadilla libre (baja)' => ['https://www.youtube.com/watch?v=pcxgEGU8QEE'],
        'Sentadilla libre (frontal)' => ['https://www.youtube.com/watch?v=27yyCF7r9hI'],
        'Zancadas (walking lunges)' => ['https://www.youtube.com/watch?v=vwTGe4b0b_o'],
        'Zancadas (estáticas)' => ['https://www.youtube.com/watch?v=pcxgEGU8QEE'],
        'Zancadas (laterales)' => ['https://www.youtube.com/watch?v=27yyCF7r9hI'],
        'Prensa de piernas (horizontal)' => ['https://www.youtube.com/watch?v=vWtlLNAXIow'],
        'Prensa de piernas (inclinada)' => ['https://www.youtube.com/watch?v=kjEyN9XHqOA'],
        'Prensa de piernas (vertical)' => ['https://www.youtube.com/watch?v=BTd1ZgKKZ3A'],
        'Extensión de cuádriceps en máquina' => ['https://www.youtube.com/watch?v=hxMsMeXTcz8'],
        'Curl femoral tumbado' => ['https://www.youtube.com/watch?v=NIng2JWF1Rs'],
        'Curl femoral sentado' => ['https://www.youtube.com/watch?v=1-aX-gHduwI'],
        'Curl femoral de pie' => ['https://www.youtube.com/watch?v=O-MLxyVYRBY'],
        'Peso muerto rumano' => ['https://www.youtube.com/watch?v=rjvlSfZ-PQw'],
        'Peso muerto piernas rígidas' => ['https://www.youtube.com/watch?v=6cwyXvlKg34'],
        'Elevaciones de talones de pie (máquina)' => ['https://www.youtube.com/watch?v=vWtlLNAXIow'],
        'Elevaciones de talones sentado (sóleo)' => ['https://www.youtube.com/watch?v=kjEyN9XHqOA'],
    ],
    'Glúteos' => [
        'Hip thrust (barra)' => ['https://www.youtube.com/watch?v=LWj9YiMWJk0'],
        'Hip thrust (mancuerna)' => ['https://www.youtube.com/watch?v=Yk4UKT_y_YQ'],
        'Hip thrust (máquina)' => ['https://www.youtube.com/watch?v=fECm0V7ePFk'],
        'Puente de glúteos en suelo' => ['https://www.youtube.com/watch?v=LWj9YiMWJk0'],
        'Puente de glúteos en banco' => ['https://www.youtube.com/watch?v=Yk4UKT_y_YQ'],
        'Sentadilla búlgara' => ['https://www.youtube.com/watch?v=vwTGe4b0b_o'],
        'Peso muerto rumano (glúteos)' => ['https://www.youtube.com/watch?v=NIng2JWF1Rs'],
        'Peso muerto a una pierna' => ['https://www.youtube.com/watch?v=1-aX-gHduwI'],
        'Patada de glúteo en máquina' => ['https://www.youtube.com/watch?v=O-MLxyVYRBY'],
        'Patada de glúteo en polea' => ['https://www.youtube.com/watch?v=rjvlSfZ-PQw'],
        'Abducciones en máquina' => ['https://www.youtube.com/watch?v=vWtlLNAXIow'],
        'Abducciones con banda' => ['https://www.youtube.com/watch?v=kjEyN9XHqOA'],
    ],
    'Core' => [
        'Crunch básico' => ['https://www.youtube.com/watch?v=dJqB4oA4sdA'],
        'Crunch en máquina' => ['https://www.youtube.com/watch?v=RCxikBS5Qy8'],
        'Elevación de piernas colgado' => ['https://www.youtube.com/watch?v=OsUz898onTE'],
        'Elevación de piernas en banco' => ['https://www.youtube.com/watch?v=JWUyng_c-G0'],
        'Elevación de piernas en silla romana' => ['https://www.youtube.com/watch?v=dJqB4oA4sdA'],
        'Plancha frontal' => ['https://www.youtube.com/watch?v=OsUz898onTE'],
        'Plancha lateral' => ['https://www.youtube.com/watch?v=JWUyng_c-G0'],
        'Rueda abdominal (ab wheel)' => ['https://www.youtube.com/watch?v=RCxikBS5Qy8'],
        'Rotaciones de torso con polea' => ['https://www.youtube.com/watch?v=dJqB4oA4sdA'],
        'Woodchoppers' => ['https://www.youtube.com/watch?v=OsUz898onTE'],
    ],
    'Bíceps' => [
        'Curl con barra recta' => ['https://www.youtube.com/watch?v=P6swDsMzqm0'],
        'Curl con barra Z' => ['https://www.youtube.com/watch?v=a9hli15uWiA'],
        'Curl alterno con mancuernas' => ['https://www.youtube.com/watch?v=P6swDsMzqm0'],
        'Curl sentado con mancuernas' => ['https://www.youtube.com/watch?v=a9hli15uWiA'],
        'Curl martillo' => ['https://www.youtube.com/watch?v=P6swDsMzqm0'],
        'Curl inclinado' => ['https://www.youtube.com/watch?v=a9hli15uWiA'],
        'Curl concentrado' => ['https://www.youtube.com/watch?v=P6swDsMzqm0'],
        'Curl en banco Scott (barra)' => ['https://www.youtube.com/watch?v=a9hli15uWiA'],
        'Curl en banco Scott (mancuerna)' => ['https://www.youtube.com/watch?v=P6swDsMzqm0'],
        'Curl en polea baja (agarre recto)' => ['https://www.youtube.com/watch?v=a9hli15uWiA'],
        'Curl en polea baja (cuerda)' => ['https://www.youtube.com/watch?v=P6swDsMzqm0'],
    ],
    'Tríceps' => [
        'Fondos en paralelas (tríceps)' => ['https://www.youtube.com/watch?v=ICaZxO7RmKs'],
        'Press cerrado en banca' => ['https://www.youtube.com/watch?v=jlFl7WJ1TzI'],
        'Extensiones de tríceps overhead con mancuerna' => ['https://www.youtube.com/watch?v=GeLq8cMODLc'],
        'Extensiones de tríceps overhead con polea' => ['https://www.youtube.com/watch?v=uEtiwYaT3d0'],
        'Jalón de tríceps en polea (barra recta)' => ['https://www.youtube.com/watch?v=br7XVh4AmUA'],
        'Jalón de tríceps en polea (cuerda)' => ['https://www.youtube.com/watch?v=ICaZxO7RmKs'],
        'Jalón de tríceps en polea (V)' => ['https://www.youtube.com/watch?v=jlFl7WJ1TzI'],
        'Rompecráneos (extensión acostado con barra)' => ['https://www.youtube.com/watch?v=GeLq8cMODLc'],
    ],
    'Máquinas' => [
        'Máquina de press de pecho (plano)' => ['https://www.youtube.com/watch?v=uEtiwYaT3d0'],
        'Máquina de press de pecho (inclinado)' => ['https://www.youtube.com/watch?v=br7XVh4AmUA'],
        'Máquina de press de pecho (declinado)' => ['https://www.youtube.com/watch?v=ICaZxO7RmKs'],
        'Máquina de aperturas/pájaros (pec deck)' => ['https://www.youtube.com/watch?v=jlFl7WJ1TzI'],
        'Máquina de aperturas/pájaros (contractor)' => ['https://www.youtube.com/watch?v=GeLq8cMODLc'],
        'Jalón al pecho en polea alta' => ['https://www.youtube.com/watch?v=vnpFhruEmsc'],
        'Remo en polea baja' => ['https://www.youtube.com/watch?v=Corxi8VEKjI'],
        'Máquina de press de hombros' => ['https://www.youtube.com/watch?v=jlFl7WJ1TzI'],
        'Máquina de elevación lateral de hombro' => ['https://www.youtube.com/watch?v=GeLq8cMODLc'],
        'Máquina de bíceps (curl)' => ['https://www.youtube.com/watch?v=P6swDsMzqm0'],
        'Máquina de tríceps (extensión/jalón)' => ['https://www.youtube.com/watch?v=uEtiwYaT3d0'],
        'Hack squat' => ['https://www.youtube.com/watch?v=hxMsMeXTcz8'],
        'Máquina de sentadilla pendular' => ['https://www.youtube.com/watch?v=vwTGe4b0b_o'],
        'Abducciones en máquina' => ['https://www.youtube.com/watch?v=vWtlLNAXIow'],
        'Aducciones en máquina' => ['https://www.youtube.com/watch?v=kjEyN9XHqOA'],
        'Multipower / Smith' => ['https://www.youtube.com/watch?v=vwTGe4b0b_o'],
    ],
    'Cardio' => [
        'Cinta de correr (treadmill)' => ['https://www.youtube.com/watch?v=vWtlLNAXIow'],
        'Bicicleta estática' => ['https://www.youtube.com/watch?v=kjEyN9XHqOA'],
        'Bicicleta de spinning' => ['https://www.youtube.com/watch?v=BTd1ZgKKZ3A'],
        'Elíptica' => ['https://www.youtube.com/watch?v=hxMsMeXTcz8'],
        'Remo ergómetro' => ['https://www.youtube.com/watch?v=vwTGe4b0b_o'],
        'Stepper / escaladora' => ['https://www.youtube.com/watch?v=pcxgEGU8QEE'],
    ]
];
